// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_ZxxHzb_8hP-7VTMQYoCKeb_qXQ0M50',
    appId: '1:993310732978:web:81c0747111b138eda10fab',
    messagingSenderId: '993310732978',
    projectId: 'movie-hub-b57d9',
    authDomain: 'movie-hub-b57d9.firebaseapp.com',
    storageBucket: 'movie-hub-b57d9.firebasestorage.app',
    measurementId: 'G-S638DGMN7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rhFFeUImtYeKJlq0ojTuh2jILPof_0c',
    appId: '1:993310732978:android:79c6791c109a56eea10fab',
    messagingSenderId: '993310732978',
    projectId: 'movie-hub-b57d9',
    storageBucket: 'movie-hub-b57d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnn3aZ740mO-0rKgZtaJiGY5Pyizj2zgA',
    appId: '1:993310732978:ios:ac2438f886c0ead0a10fab',
    messagingSenderId: '993310732978',
    projectId: 'movie-hub-b57d9',
    storageBucket: 'movie-hub-b57d9.firebasestorage.app',
    iosClientId: '993310732978-tinc1ki8d05aka1rfctc4qttl8b1rs87.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnn3aZ740mO-0rKgZtaJiGY5Pyizj2zgA',
    appId: '1:993310732978:ios:ac2438f886c0ead0a10fab',
    messagingSenderId: '993310732978',
    projectId: 'movie-hub-b57d9',
    storageBucket: 'movie-hub-b57d9.firebasestorage.app',
    iosClientId: '993310732978-tinc1ki8d05aka1rfctc4qttl8b1rs87.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh_ZxxHzb_8hP-7VTMQYoCKeb_qXQ0M50',
    appId: '1:993310732978:web:426c3117818602e8a10fab',
    messagingSenderId: '993310732978',
    projectId: 'movie-hub-b57d9',
    authDomain: 'movie-hub-b57d9.firebaseapp.com',
    storageBucket: 'movie-hub-b57d9.firebasestorage.app',
    measurementId: 'G-QQPW37GYMZ',
  );
}
